# Generated by Django 5.2.9 on 2026-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='service name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='price')),
                ('duration', models.DurationField(verbose_name='duration time')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='modify date')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
