# Generated by Django 5.2.9 on 2026-01-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        ('services', '0003_service_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='salon'),
        ),
    ]
