# Generated by Django 5.2.9 on 2026-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'month 1'), (2, 'month 2'), (3, 'month 3'), (4, 'month 4'), (5, 'month 5'), (6, 'month 6'), (7, 'month 7'), (8, 'month 8'), (9, 'month 9'), (10, 'month 10'), (11, 'month 11'), (12, 'month 12')], null=True, verbose_name='birth month'),
        ),
    ]
