# Generated by Django 5.2.9 on 2026-01-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_birth_month'),
        ('appointments', '0001_initial'),
        ('services', '0002_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reservation_date',
            field=models.DateField(db_index=True, null=True, verbose_name='reservation date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('done', 'Done'), ('canceled', 'Canceled')], default='reserved', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='appointments.appointment', verbose_name='appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
