# Generated by Django 5.2.9 on 2026-01-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_note_appointment_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentservice',
            options={'verbose_name': 'appointment service', 'verbose_name_plural': 'appointment services'},
        ),
    ]
