# Generated by Django 5.2.9 on 2026-01-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointmentservice_options'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='salon'),
        ),
    ]
