# Generated by Django 5.2.9 on 2026-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='salon name')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='owner name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('subscription_expire_at', models.DateField(blank=True, null=True, verbose_name='subscription expire date')),
                ('sms_provider', models.CharField(default='dummy', max_length=50, verbose_name='sms provider')),
                ('sms_sender', models.CharField(blank=True, max_length=50, verbose_name='sms sender number')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, verbose_name='sms api key')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='support phone')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salons',
            },
        ),
    ]
