# Generated by Django 5.2.9 on 2026-01-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_birth_month'),
        ('appointments', '0002_appointment_note_appointment_reservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('message', models.TextField(help_text='can use variables like {{name}}, {{date}}, {{time}}', verbose_name='formated message')),
                ('type', models.CharField(choices=[('appointment_confirm', 'appointment confirm'), ('appointment_reminder', 'appointment reminder'), ('birthday', 'birthday'), ('promotion', 'promotion'), ('custom', 'custom')], max_length=30, verbose_name='template type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('message', models.TextField(verbose_name='final message')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=10, verbose_name='status')),
                ('provider_response', models.TextField(blank=True, verbose_name='provider response')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment', verbose_name='appointment')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='customer')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.smstemplate', verbose_name='template')),
            ],
        ),
    ]
