# Generated by Django 5.2.9 on 2026-01-20 12:51

from django.db import migrations

import json
from django.conf import settings
from pathlib import Path


def load_sms_templates(apps, schema_editor):
    SMSTemplate = apps.get_model('notifications', 'SMSTemplate')
    data_path = Path(settings.BASE_DIR) / 'data' / 'sms_templates.json'
    print(f" {data_path}")

    with open(data_path, 'r', encoding='utf-8') as f:
        templates = json.load(f)

    for item in templates:
        SMSTemplate.objects.update_or_create(
            title=item['title'],
            defaults={
                'type': item['type'],
                'is_active': item['is_active'],
                'message': item['message']
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_sms_templates),
    ]

