# Generated by Django 5.2.9 on 2026-01-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20260120_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'verbose_name': 'sms log', 'verbose_name_plural': 'sms logs'},
        ),
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'verbose_name': 'sms template', 'verbose_name_plural': 'sms templates'},
        ),
    ]
