# Generated by Django 5.2.9 on 2026-01-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_smslog_salon_smstemplate_salon'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='salon'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='salon'),
        ),
    ]
